### ISSUE TITLE
userstore - set?

### ISSUE THREAD

**Issue by zgrguric** [XRPL-Labs/Developer-Help-Center#5]
https://github.com/XRPL-Labs/Developer-Help-Center/blob/main/js-ts-sdk/sdk-syntax/xumm.userstore-.../set-...-....md

Executing 'set' on existing key overwrites previous stored value?
When executing this one after another:
```
xumm.userstore.set('userdetails', { name: 'Jane', gender: 'F' })
// { name: 'Jane', gender: 'F' }
xumm.userstore.set('userdetails', { name: 'Jane2', gender: 'F' })
// Will store this (overwrite?): { name: 'Jane2', gender: 'F' }
```

**Comment by WietseWind** [comment]
Correct, it overwrites the full value. It's a key value store.
